### ISSUE TITLE
Can't make it work on iOS when script async

### ISSUE THREAD

**Issue by kud** [googleads/googleads-ima-html5#1]
```javascript
loadSdk: function() {
    var script = document.createElement('script')
    script.setAttribute('src', '//imasdk.googleapis.com/js/sdkloader/ima3_debug.js') // debugging mode

    script.onload = this.requestAds.bind(this)

    document.getElementsByTagName('head')[0].appendChild( script )
}
```

I'm doing this but on iOS (only?) it doesn't work:

```
" [  0.728s] [ima.loader.AdSourceFetcher] Creating VastAdSource." bridge3.95.1_debug_en.html:483

" [  0.731s] [ima.loader.VastAdSource] hasMoreAds, this.ads.length: 1 , this.currentAdIndex: -1" bridge3.95.1_debug_en.html:483

" [  0.733s] [ima.loader.VastAdSource] getNextAd, this.currentAdSource: null" bridge3.95.1_debug_en.html:483

" [  0.734s] [ima.loader.VastAdSource] hasMoreAds, this.ads.length: 1 , this.currentAdIndex: -1" bridge3.95.1_debug_en.html:483

" [  0.737s] [ima.loader.VastAdSource] processNextAd_, currentAdIndex: 0, ads.length: 1" bridge3.95.1_debug_en.html:483

" [  0.740s] [ima.loader.VastAdSource] processInlineAd, successCallback with 1 ads" bridge3.95.1_debug_en.html:483

" [  0.742s] [ima.loader.VastAdSource] hasMoreAds, this.ads.length: 1 , this.currentAdIndex: 0" bridge3.95.1_debug_en.html:483

" [  0.744s] [ima.loader.AdsLoaderImpl] exhaustAdSource_, calling success for 1 ads" bridge3.95.1_debug_en.html:483

" [  0.746s] [ima.loader.AdsLoaderWrapper] dispatchAdsManagerLoadedEvent_, ads.length: 1" bridge3.95.1_debug_en.html:483

" [  0.749s] [ima.managers.AdsManagerFactory] createAdsManager, adType: video" bridge3.95.1_debug_en.html:483

" [  0.945s] [ima.managers.BaseAdsManager] Could not display companion ads." bridge3.95.1_debug_en.html:483

" [ 15.952s] [ima.vast.VideoAdEventTracker] dispatching event mediaLoadTimeout" bridge3.95.1_debug_en.html:483

" [ 15.957s] [ima.managers.VastVideoAdsManager] Playback error: [object Object]" bridge3.95.1_debug_en.html:483

" [ 15.969s] [ima.common.ErrorUtils] Error play dispatched: AdError 402: VAST media file loading reached a timeout of 15 seconds."
```

It works though I do not add the script async, but add it directly in the dom. Any idea?

**Comment by shawnbuso** [comment]
Are you calling initializeAdDisplayContainer anywhere? If not requestAds will call it for you, but it must be called as a result of a user action (button click, etc.) on iOS. If you're not calling it then it's being called here as a result of requestAds, which here is being called as a result of the script loading, which is not a user action, so that's your problem.

**Comment by kud** [comment]
Okay, thank you for your explanation. I will try tomorrow. ;)

On 14 April 2015 at 21:38, Shawn Busolits <notifications@github.com> wrote:

> Are you calling initializeAdDisplayContainer anywhere? If not requestAds
> will call it for you, but it must be called as a result of a user action
> (button click, etc.) on iOS. If you're not calling it then it's being
> called here as a result of requestAds, which here is being called as a
> result of the script loading, which is not a user action, so that's your
> problem.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/googleads/googleads-ima-html5/issues/1#issuecomment-93034037>
> .
>



-- 
*Erwann Mest*
kud.io
