### ISSUE TITLE
Bug with subtitles/HLS on IPHONE

### ISSUE THREAD

**Issue by larryaubstore** [googleads/googleads-ima-html5#10]
I created a pull request to show the bug: https://github.com/googleads/googleads-ima-html5/pull/9

To reproduce the bug:

- Click on on first item of the playlist on IPHONE devices.
- The preroll will play.
- The content never start. 

The first item of the playlist don't play with subtitles but play without subtitles.
The second item of the playlist is always playing fine with subtitles and without subtitles. 

Both item of the playlist contains on-demand HLS videos. 

If you don't inject the vtt file, both items of the playlist are playing fine.

**Comment by shawnbuso** [comment]
Taking a closer look at this, it looks like the issue doesn't have anything to do with IMA, but rather your captions file. I set up a simple test page that just tries to load the video with captions, and playback fails on iPhone:

    <html>
      <body>
        <video id="contentElement">
          <source src="https://toutvuniver1-vh.akamaihd.net/i/012/mp4/b/2006-07-16_07_15_00_bouleetbill_0103_,500,800,1200,.mp4.csmil/master.m3u8?hdnea=st=1453503925~exp=1456095925~acl=/i/012/mp4/b/2006-07-16_07_15_00_bouleetbill_0103_*~hmac=73e8aea1e8a62fdf4f2fe51386838e588342d6b9e7e86affa9528b5bc40341ae">
          <track kind="captions" label="English" srclang="fr" src="3453.vtt">
        </video>
      </body>
    </html>

If I remove the captions file here it plays fine.

**Comment by larryaubstore** [comment]
You're partially right :) The caption file is good, but the 'bouleetbill' hls file seem to be problematic on a specific scenario. If I inject the vtt dynamically there is no error. However, if I load the vtt statically there is an error.

I updated the pull request and I added a few tests:

- TestPlayBackDynamic.html (I click on button to inject a track before starting the video and everything is fine)
- TestPlayBackError.html (Everything is loaded statically, I got an error on video start)
- TestPlayBackNoError.html (Everything is loaded statically, stream different, not 'bouleetbill', no error on on video start)

Now, I understand better the problem, I will try to investigate what happens with the 'bouleetbill' stream on my side. I agree with you, at the end it's not really a bug related to IMA. 

I don't know if you can something on your side. Maybe if you inject vtt files dynamically ... But, I agree again with you, it is a bug with the stream ...

**Comment by shawnbuso** [comment]
I'm not sure exactly what the problem is, but the iPhone implementation of the SDK uses the same player for ads and content, so it could have something to do with the way the SDK is loading the stream. If you get your subtitles working or find another example of working subtitles with the same problem, could you post to our [forum](https://groups.google.com/forum/#!forum/ima-sdk) and we can help from there? Thanks!
