### ISSUE TITLE
Failed to execute 'play' on 'HTMLMediaElement': API can only be initiated by a user gesture.

### ISSUE THREAD

**Issue by DanielDeychakiwsky** [googleads/googleads-ima-html5#11]
Hey there,

Hope all is well.

When testing on Android Chrome I have recently started getting the following error:

`Failed to execute 'play' on 'HTMLMediaElement': API can only be initiated by a user gesture.`

I'm calling `initialize` as instructed and I'm correctly passing in my container and videoSlot to the AdDisaplyContainer.

Just wanted to sanity check with you - there are no bugs that you are aware of?

**Comment by shawnbuso** [comment]
Is this with one of these samples or your own implementation? If a sample, which one? If your own implementation, please use our [support forum](https://groups.google.com/forum/?hl=en_US&fromgroups=#!forum/ima-sdk) for better assistance.
