### ISSUE TITLE
Can't scroll page when touching video element while playing vast

### ISSUE THREAD

**Issue by Avien** [googleads/googleads-ima-html5#12]
When debugging on chrome I get the following exceptions:

"Uncaught TypeError: document.createTouch is not a function"
"Uncaught TypeError: Cannot read property 'apply' of undefined"
![image](https://cloud.githubusercontent.com/assets/4569044/13555253/25d4e464-e3c4-11e5-84ad-b30389d14c9b.png)

Which probably prevents the touchmove event

In vPaid it does not happen (probably different code flow)

**Comment by shawnbuso** [comment]
Hi there,

Could you post this to our [support forum](https://groups.google.com/forum/?hl=en_US&fromgroups#!forum/ima-sdk)? That's where we do our support and you'll get a much better and faster response there. Thanks!

**Comment by Avien** [comment]
Just did, 10x
