### ISSUE TITLE
Linear assets were found in the VAST ad response, but none of them matched the video player's capabilities

### ISSUE THREAD

**Issue by ZohaibGhafoor** [googleads/googleads-ima-html5#14]
Linear assets were found in the VAST ad response, but none of them matched the video player's capabilities error in Opera browser

**Comment by shawnbuso** [comment]
Hi there,

This sounds like an error with the SDK in general and not specifically these samples - could you post this info with the tag you're using to our [support forum](https://groups.google.com/forum/?hl=en_US&fromgroups#!forum/ima-sdk)?

Thanks!
