### ISSUE TITLE
can not play ad in iphone.

### ISSUE THREAD

**Issue by ZohaibGhafoor** [googleads/googleads-ima-html5#15]
Hi Shawn,
i am trying to play ad in iphone safari browser but it is not able to play the ad. may be the problem is youtube api iframe flash player. please suggest me what should i do now?

**Comment by ZohaibGhafoor** [comment]
Sorry the sample tag is working fine but when i place my own tag it plays once then it will stop playing the ad. vast tag become empty. why is this?

**Comment by shawnbuso** [comment]
Hi there,

Since this appears to be an issue with your tag and not the sample itself, could you post in our [support form](https://groups.google.com/forum/?hl=en_US&fromgroups#!forum/ima-sdk)? Thanks!
