### ISSUE TITLE
can i play ad inside content player instead of another ad player?

### ISSUE THREAD

**Issue by ZohaibGhafoor** [googleads/googleads-ima-html5#16]
can i play ad video inside main videoplayer instead of ima player which come top of the videoplayer ?

**Comment by shawnbuso** [comment]
Hi there,

It sounds like this question is related to the SDK in general, and not specifically an issue with these examples. You'll get a better response if you ask this on our [support forum](https://groups.google.com/forum/?hl=en_US&fromgroups#!forum/ima-sdk).

Thanks!
Shawn
