### ISSUE TITLE
VMAP with non linear overlay iOS emptied problem

### ISSUE THREAD

**Issue by hyurtseven81** [googleads/googleads-ima-html5#17]
When i try the following vmap with the advanced or other examples, on iPad preroll works perfectly but when overlay or fullslot ads start player fires emptied event and video starts from the beginning.

`<?xml version="1.0" encoding="utf-8"?>
<vmap:VMAP version="1.0" xmlns:vmap="http://www.iab.net/videosuite/vmap">
  <vmap:AdBreak timeOffset="start" breakType="linear" breakId="preroll">
    <vmap:AdSource id="preroll-ad-1" allowMultipleAds="false" followRedirects="true">
      <vmap:AdTagURI templateType="vast3">
        <![CDATA[https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dlinear&correlator=]]>
      </vmap:AdTagURI>
    </vmap:AdSource>
  </vmap:AdBreak>
  <vmap:AdBreak timeOffset="00:00:20.000" breakType="nonlinear" breakId="overlay">
    <vmap:AdSource id="overlay-ad-3" allowMultipleAds="false" followRedirects="true">
      <vmap:AdTagURI templateType="vast3">
        <![CDATA[https://pubads.g.doubleclick.net/gampad/ads?sz=480x70&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dnonlinear&correlator=]]>
      </vmap:AdTagURI>
    </vmap:AdSource>
  </vmap:AdBreak>
  <vmap:AdBreak timeOffset="00:00:40.000" breakType="linear" breakId="middroll">
    <vmap:AdSource id="middroll-ad-4" allowMultipleAds="false" followRedirects="true">
      <vmap:AdTagURI templateType="vast3">
        <![CDATA[https://googleads.g.doubleclick.net/pagead/ads?client=ca-video-pub-6042571565839072&slotname=8759539312/3322294072&ad_type=text_image_flash&description_url=http%3A%2F%2Fkanald.com.tr&max_ad_duration=30000&videoad_start_delay=0]]>
      </vmap:AdTagURI>
    </vmap:AdSource>
  </vmap:AdBreak>
  <vmap:AdBreak timeOffset="end" breakType="linear" breakId="postroll">
    <vmap:AdSource id="postroll-ad-7" allowMultipleAds="false" followRedirects="true">
      <vmap:AdTagURI templateType="vast3">
        <![CDATA[https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/9927946/kanald/programlar/postroll&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&url=[referrer_url]&description_url=[description_url]&correlator=[timestamp]]]>
      </vmap:AdTagURI>
    </vmap:AdSource>
  </vmap:AdBreak>
</vmap:VMAP>
`

**Comment by shawnbuso** [comment]
The IMA SDK currently doesn't support overlay ads in a VMAP response - are you seeing any issues if you remove the overlay ad? You can see more about supported features [here](https://developers.google.com/interactive-media-ads/docs/sdks/html5/compatibility).

**Comment by hyurtseven81** [comment]
I think i've find the problem,

When overlay ad starts ima3.js fires video.load() event and this causes the problem, but when i disabled the restoreCustomPlaybackStateOnAdBreakComplete option there is no problem and player can play overlays and fullslot midrolls without any problem.

So i think my problem's solved with changing the following parameter:
adsRenderingSettings.restoreCustomPlaybackStateOnAdBreakComplete = false;

I tested all ad formats on desktop browsers, android and iOs platforms it seems there is no problem.

Thank you.
