### ISSUE TITLE
Enable VPAID 2 support by default in all examples

### ISSUE THREAD

**Issue by bluepuma77** [googleads/googleads-ima-html5#18]
Flash has been pronounced dead by most media in 2015, Google AdWords officially announced it in February 2016, that Flash ads will be disabled for new campaigns ["Starting June 30th, 2016"](https://plus.google.com/+GoogleAds/posts/dYSJRrrgNjk).

In my opinion it's time to move from Flash to Javascript creatives and enable VPAID2 Javascript by default in all examples. It's documented here ["Enabling VPAID 2 support"](https://developers.google.com/interactive-media-ads/docs/sdks/html5/vpaid2js). Thanks.

**Comment by shawnbuso** [comment]
The SDK now defaults to allowing VPAID 2.0 creatives, so we don't need to do anything special in the samples for them to work.
