### ISSUE TITLE
Prerolls do not play when using multiple players on the page

### ISSUE THREAD

**Issue by saxena-gaurav** [googleads/googleads-ima-html5#2]
I have 2 video.js players on a page. When I click on play button on the first player, ads do not play. Basically I referred to this example https://github.com/googleads/videojs-ima/blob/master/examples/simple/index.html and added 2nd player. Could this possibly be an issue with IMA SDK? Here is a link to my test page : http://solutions.brightcove.com/gsaxena/ima/

**Comment by shawnbuso** [comment]
Hi there,

The best place to get support for our products is via the forum - we try to reserve the issue tracker for things that are confirmed bugs or feature requests. 

Are you using the [video.js IMA plugin](https://github.com/googleads/videojs-ima)? If so, the best place to get support is [here](https://groups.google.com/forum/?hl=en_US&fromgroups#!forum/google-media-framework).

If you're doing your own IMA implementation, the we have [this forum](https://groups.google.com/forum/?hl=en_US&fromgroups#!forum/ima-sdk) to support IMA developers.

Thanks,
Shawn

**Comment by saxena-gaurav** [comment]
@shawnbuso : Thanks . Posted the question on forum:

https://groups.google.com/forum/?hl=en_US&fromgroups#!topic/google-media-framework/pmJefC7YCa4
