### ISSUE TITLE
i have follow this in my customized player

### ISSUE THREAD

**Issue by nafisakanwal** [googleads/googleads-ima-html5#20]
I have follow this example into my own customized player ,

<div id="mainContainer">
<div id="content">
<video id="contentElement" width="640" height="360" src="test.mp4" preload="metadata"></video>
<div id="videoPosterContainer" class="videoPosterContainer show">
</div>
<div id="adContainer"></div>
</div>

But i am getting this error although i have same html structure of my player 
uncaught exception: AdError 1101: The provided containerElement information: element is invalid.

Can anyone help me please 
Thankyou in advance

**Comment by shawnbuso** [comment]
Hi there,

This issue tracker is for issues specifically with the samples, not other implementations. For your implementation, could you post in our [support forum](https://groups.google.com/forum/?hl=en_US&fromgroups#!forum/ima-sdk)?

Thanks!
Shawn
