### ISSUE TITLE
Simple example does not work in MS Edge

### ISSUE THREAD

**Issue by osmestad** [googleads/googleads-ima-html5#21]
We are trying to use the SDK but are having problems in MS Edge, the same problem seems to happen in your simple example:
http://googleads.github.io/googleads-ima-html5/simple/

In browser console we get:
[object Object]AdError 400: There was an error playing the video ad. Caused by: Error: [object MediaError]

Tested browser:
Microsoft Edge 38.14393.0.0
Microsoft EdgeHTML 14.14393

(Might be related to this issue: https://github.com/googleads/videojs-ima/issues/98 )

**Comment by TheHaff** [comment]
+1

**Comment by shawnbuso** [comment]
Thanks for the info - this is a known issue with our test ads (not an issue with the SDK itself). Once we get that issue resolved ads should be working again on MS Edge.

**Comment by osmestad** [comment]
Okay, I saw you had a suggestion on forcing Flash in the other issue, if that is a possible workaround, would that be something like:
```
adsManager = adsManagerLoadedEvent.getAdsManager(
        videoContent,
        {mimeTypes: ['application/x-shockwave-flash']}
      );
```

(I tried but for that I get: ```adsManager = AdError 900: Invalid usage of the API. Cause: Invalid or unsuppoted mime type application/x-shockwave-flash``` )

**Comment by shawnbuso** [comment]
The HTML5 SDK doesn't support Flash video ads, only Flash VPAID ads, so forcing Flash won't work. You should, however, be able to force one of the other non-Flash video types. Our test tags return 'video/3gpp', which is supported by MS Edge. The MS Edge docs say they support webm as well, but our SDK doesn't attempt that because calling canPlayType('video/webm') on the MS Edge video player returns an empty strings, which means that the player does not support that mime type.

**Comment by cytrowski** [comment]
So according to what @osmestad said, we need that:

```javascript
adsManager = adsManagerLoadedEvent.getAdsManager(
  videoContent,
  { mimeTypes: ['video/3gpp'] }
);
```

Right?

**Comment by shawnbuso** [comment]
For the sample ad request yes, that will work. To be clear this is related to how our CDN is returning the mp4 file in this sample - other mp4 files may or may not work depending on how your CDN is serving them. When you change the ad tag from our sample tag to your production tag, I would test without this to see if it works, and only add it back in if it doesn't work.

**Comment by cytrowski** [comment]
I see that it will fail if I pass more than one mimeType there - that's because HTML5 SDK recognises IE/Edge capabilities incorrectly? It looks like when I add 'video/mp4' too it tries to use that mime instead.

**Comment by shawnbuso** [comment]
Right, we don't have asset-level fallback, so if you pass more than one mimeType it will pick the one it thinks is best and try to play that. If that fails, we *don't* try to play the other mimeType, we just throw an error.

**Comment by cytrowski** [comment]
Ok, the `3gpp` seems to work on Edge. However on IE11 none of `3gpp`, `x-flv`, `webm` works. The VAST document has all of them ready to go though. I tried those formats based on this thread: https://groups.google.com/forum/#!topic/ima-sdk/iYOgCVlm2k4

**Comment by shawnbuso** [comment]
Are you testing with our test tag still or your own tag? This issue seems to be on a tag-to-tag basis, so I'd suggest testing with your own tag to see if it's working.

**Comment by cytrowski** [comment]
I'm afraid I don't get what do you mean by tag. Can you bring some examples here? I assume we are not talking about some HTML stuff, right? Where do I have an option to choose tag? Do I have one? Is it something that comes with VAST response?

**Comment by shawnbuso** [comment]
That ad tag is what you provide to get ads - in the simple example, that's [here](https://github.com/googleads/googleads-ima-html5/blob/master/simple/ads.js#L37). The tag we provide is just a sample - it won't make you any money. You'll need to work with an ad server to get an ad tag of your own that will return ads that make money for you.

**Comment by cytrowski** [comment]
Ok, I get it. Thanks for help. I'm looking forward for IE/Edge capabilities detection fix :)
