### ISSUE TITLE
[Question] Where is VAST video ad started event ?

### ISSUE THREAD

**Issue by kslimani** [googleads/googleads-ima-html5#22]
Hi,

The AdEvent types are described [here](https://developers.google.com/interactive-media-ads/docs/sdks/html5/v3/apis#ima.AdEvent.Type) but i can't figure which one is the VAST video ad started ? (_especially when it is a VPAID which play video ad_)

According [IAB VPAID 2.0 documentation](https://www.iab.com/wp-content/uploads/2015/06/VPAID_2_0_Final_04-10-2012.pdf), the `AdStarted` event (`google.ima.AdEvent.type.STARTED` ?) is fired as the result of calling the startAd() VPAID method. (ad unit started)

But i can't find in documentation the IMA equivalent to VAST `AdVideoStart` event : 

```
AdStarted             -->  google.ima.AdEvent.type.STARTED
AdImpression          -->  google.ima.AdEvent.type.IMPRESSION
AdVideoStart          -->  ???
AdVideoFirstQuartile  -->  google.ima.AdEvent.type.FIRST_QUARTILE
AdVideoMidpoint       -->  google.ima.AdEvent.type.MIDPOINT
AdVideoThirdQuartile  -->  google.ima.AdEvent.type.THIRD_QUARTILE
AdVideoComplete       -->  google.ima.AdEvent.type.COMPLETE
```

Does someone have a clue ?

**Comment by shawnbuso** [comment]
Hey there,

The event you're looking for is google.ima.AdEvent.type.STARTED. If you have any more questions let me know!

Thanks,
Shawn Busolits
IMA SDK Team

**Comment by kslimani** [comment]
@shawnbuso : if `google.ima.AdEvent.type.STARTED` is VAST`AdVideoStart` then which Google IMA event is VAST `AdStarted` event ?

**Comment by shawnbuso** [comment]
We re-use that event for both - we don't necessarily have a 1:1 mapping for VAST events to SDK events. So when we fire AdStrted and AdVideoStart as VAST events, we fire AdStarted as an SDK event.

**Comment by kslimani** [comment]
I think i understand.

So basically, for some linear the STARTED SDK event is VAST AdStarted and for some VPAID the STARTED SDK event is VAST AdStarted ?

If that's the case, to known if an ad beeing displayed, should i rely on SDK IMPRESSION event ?

**Comment by shawnbuso** [comment]
If all you're concerned with is whether or not an ad is on the screen, you should use STARTED and COMPLETE.

**Comment by kslimani** [comment]
Allright, so a successfully displayed ad is if the STARTED __and__ COMPLETE SDK events have bneen triggered. Does the COMPLETE event is fired even if user "SKIP" the ad ?

**Comment by shawnbuso** [comment]
Good catch - it is not. So you'll need to check for COMPLETE or SKIPPED.

**Comment by kslimani** [comment]
Thank you @shawnbuso that's more clear to me.

I will do more tests with these infos. The re-use of STARTED should be added to SDK documentation, i had hard time to figure out why this event was fired by tier VPAID on ad inventory response.

**Comment by shawnbuso** [comment]
Thanks for the feedback - I'm going to close this case out but feel free to re-open it if you need additional help.
