### ISSUE TITLE
[Question] I have a question of IMA support format.

### ISSUE THREAD

**Issue by soso851213** [googleads/googleads-ima-html5#23]
Hello, I have a simple question.
I use ima3 to load mpegdash format in Chrome browser, It can't play advert.
But it can play in Edge browser.

this problem is normal?
Thank you for considering my request.

**Comment by shawnbuso** [comment]
Hi there,

Since this isn't a problem specifically with these samples, could you post in our [support form](https://groups.google.com/forum/?fromgroups#!forum/ima-sdk)?

Thanks,
Shawn Busolits
IMA SDK Team
