### ISSUE TITLE
Ad error: AdError 1009: The VAST response document is empty.

### ISSUE THREAD

**Issue by bharathsn0812** [googleads/googleads-ima-html5#25]
Hi Team,

AD URL

> https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/34852230/bollywoodbubblevideos&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&url=[referrer_url]&description_url=http%3A%2F%2Fbollywoodbubblevideos.com&correlator=[timestamp]

i am getting "**Ad error: AdError 1009: The VAST response document is empty.**" for "advanced" and "simple" examples, But the same ad url plays in google vast inspector

**Comment by shawnbuso** [comment]
Hi there - we support this product via our [support forum](https://groups.google.com/group/ima-sdk) - would you mind posting there? Thanks!

**Comment by bharathsn0812** [comment]
Hi Shawnbuso,

Have posted in support forum
https://groups.google.com/forum/#!topic/ima-sdk/RIKWUdchnjY

Thanks and Regards
BHARATH SN

**Comment by shawnbuso** [comment]
Thanks!
