### ISSUE TITLE
Simple example not rendering post-roll VMAP ads

### ISSUE THREAD

**Issue by bharathsn0812** [googleads/googleads-ima-html5#26]
Hi Team,

Have used ad url "https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpost&cmsid=496&vid=short_onecue&correlator=" 
which is VMAP xml contains pre-roll, midroll (15s) , post-roll ad

Player plays pre-roll and midroll fine. But not post-roll ad
Have used various VMAP ad urls provided by google ima sdk "https://developers.google.com/interactive-media-ads/docs/sdks/html5/tags" and facing issue with post-roll ad

Used simple example provided in github

Thanks and Regards
BHARATH SN

**Comment by shawnbuso** [comment]
It looks like we're missing the call to contentComplete that we have in the getting started guide. I'm fixing this now - in the meantime you can look at our contentComplete call in the advanced example for post-roll support. Thanks!

**Comment by bharathsn0812** [comment]
Hi Shawn,

VAMP post-roll ads appearing now for simple example
Thank u for quick response.


Thanks and Regards
BHARATH SN
