### ISSUE TITLE
Wrapper tracking urls

### ISSUE THREAD

**Issue by znata** [googleads/googleads-ima-html5#27]
I've created an xml with one Wrapper element, that redirect to other Inline ad.
Both of them have one Tracking event=start.
VASTv3_0 says that all ad server in chain should be pinged with tracking urls. But when the ad started only Inline.Tracking event will be pinged.

**Comment by shawnbuso** [comment]
Hi there,

Would you mind posting this on our [official support forum](https://groups.google.com/group/ima-sdk)? You'll get a faster response there.

Thanks,
Shawn
