### ISSUE TITLE
broken with latest release for videojs

### ISSUE THREAD

**Issue by bpletzer** [googleads/googleads-ima-html5#28]
Dear @shawnbuso 

with the release of 1 1/2 weeks ago google ima sdk is kinda broken for us.

We are using videojs with your videojs-ima plugin. We actually are on the latest tag (0.8.0, unfortunatelly it is cloaking itself as 0.7.0 in videojs), but since few days only - so we don't think upgrading from videojs-ima github tag 0.6.0 to 0.8.0 did break the behaviour nor did it improve the situation.

We do but think that for some reason the ima sdk does not reuqest ad-video in all cases anymore - one sees the xml-file-reuqest, but no ad-file is done subsequently. This is being true for 15% of our traffic now.

Love to get in touch with you on how to best communicate this issue.

regards
Benedikt

**Comment by shawnbuso** [comment]
Hey Benedikt,

Since you're using the video.js plugin, could you report this on [that issue tracker](https://github.com/googleads/videojs-ima/issues)?

Also, if you could include a sample page and reproduction steps for us to troubleshoot on our end it would be super helpful.

Thanks!
Shawn
