### ISSUE TITLE
IMA SDK Loading

### ISSUE THREAD

**Issue by aydinkn** [googleads/googleads-ima-html5#3]
Hi,

In the simple example index.html, ima sdk script:
```
<script type="text/javascript" src="//imasdk.googleapis.com/js/sdkloader/ima3.js"></script>
```
But in the advanced example index.html:
```
<script type="text/javascript" src="//s0.2mdn.net/instream/html5/ima3.js"></script>
```

What is difference? Which is right choose?

**Comment by ypavlotsky** [comment]
Hi,

Please use the imasdk.googleapis.com domain, it is the preferred domain now. Thanks.

**Comment by aydinkn** [comment]
Ok, thanks
