### ISSUE TITLE
Unable to click for VPAID sample

### ISSUE THREAD

**Issue by ninja-ja** [googleads/googleads-ima-html5#30]
I recently test the VPAID sample ([Single VPAID 2.0 Linear](https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ct%3Dlinearvpaid2js&correlator=)) on [IMA Sample Tags page](https://developers.google.com/interactive-media-ads/docs/sdks/html5/tags) using [Video Suite Inspector](https://developers.google.com/interactive-media-ads/docs/sdks/html5/vastinspector).
The video can play but not clickable.
I've checked the sample tag which has ClickTracking url embedded. To my knowledge, video player should respect this setting and follows the url when user clicks video.

Does someone know why this is not functioning?

![not_clickable](https://user-images.githubusercontent.com/1926315/37273969-47637bf4-2616-11e8-9d24-dcf726d18c03.png)

**Comment by shawnbuso** [comment]
Hi there - it sounds like this is an issue with your IMA implementation, not specifically these samples. Could you post over on our [support forum](https://groups.google.com/forum/#!forum/ima-sdk)? Thanks!

**Comment by ninja-ja** [comment]
I've posted the question to the forum.
Thanks!
