### ISSUE TITLE
[Question] AdsLoader re-use mechanism

### ISSUE THREAD

**Issue by kslimani** [googleads/googleads-ima-html5#33]
On [SDK documentation page](https://developers.google.com/interactive-media-ads/docs/sdks/html5/#requestAds), it is recommanded to use the same AdsLoader instance for the entire lifecycle of page.

I am working on a web project where user interactions with GUI creates new video elements without changing page. (and destroy previously created)

AdsLoader constructor require an AdDisplayContainer instance which itself accepts an optional HTMLVideoElement. In my case, the HTMLVideoElement should be the newly created video element.

My issue here is that AdsLoader seems to have ~~to~~ no method to set/replace AdDisplayContainer instance.

I would like to know, if it is an acceptable solution to destroy AdDisplayContainer and AdsLoader and re-create them for each newly created video element ? (or should I expect to have issues ?)

**Comment by shawnbuso** [comment]
Hi there,

It looks like your question is about the SDK in general, and not specific to these samples. Could you post your issue on our [discussion forum](https://groups.google.com/group/ima-sdk)? We have a team of folks who monitor that closely and will get back to you quickly :)

Thanks,
Shawn
