### ISSUE TITLE
Controls are not displaying on HTML 5 Player when IMA is integrated

### ISSUE THREAD

**Issue by chandanluthra** [googleads/googleads-ima-html5#34]
Controls are not getting displayed on HTML 5 Player when IMA is integrated.
I even tried to seek out the help from the examples but haven't got success. The examples that are mentioned in this repo uses the custom controls out side the player.

**Comment by shawnbuso** [comment]
Hi there - this sounds like an issue with your implementation, not these samples. If so, could you post on our [support forum](https://groups.google.com/group/ima-sdk)? You'll get better help there. Thanks!
