### ISSUE TITLE
about IMA's usage problem

### ISSUE THREAD

**Issue by lynxerzhang** [googleads/googleads-ima-html5#35]
[flvjs is a HTML5 FLV Player](https://github.com/Bilibili/flv.js/)

Below is flvjs's Features
1. FLV container with H.264 + AAC / MP3 codec playback
2. Multipart segmented video playback
3. HTTP FLV low latency live stream playback
4. FLV over WebSocket live stream playback
5. Compatible with Chrome, FireFox, Safari 10, IE11 and Edge
6. Extremely low overhead, and hardware accelerated by your browser!

and I want to ask is it could use Google IMA SDK？（Live broadcast for example）

and I found title 'Request video ads' with below code

```javascript
// Request video ads.
var adsRequest = new google.ima.AdsRequest();
adsRequest.adTagUrl = 'https://pubads.g.doubleclick.net/gampad/ads?' +
    'sz=640x480&iu=/124319096/external/single_ad_samples&ciu_szs=300x250&' +
    'impl=s&gdfp_req=1&env=vp&output=vast&unviewed_position_start=1&' +
    'cust_params=deployment%3Ddevsite%26sample_ct%3Dlinear&correlator=';
```
I want to ask what is adTagUrl , and where it come from?

**Comment by Kiro705** [comment]
Hello @lynxerzhang ,

The `adTagUrl` is the URL used in an ad request to target specific ad line items, either in Google Ad Manager or another ad inventory. Simply, this is the URL which determines which ad/ads will play.

I would expect the IMA SDK would work with the FLV player for client-side ads. The IMA SDK will overlay a second video player for ads, so the content video player should not greatly affect this

Please feel free to reopen this issue if you have any farther questions.
