### ISSUE TITLE
VPAID example

### ISSUE THREAD

**Issue by supersh86** [googleads/googleads-ima-html5#37]
Hi
Help I did not understand how to use the vpaid sample.
Where can I find the documentation?
How to connect the vast xml stream to this script?

**Comment by Kiro705** [comment]
Hello @supersh86 ,

The code for the 2 VPAID samples is used indirectly by the [IMA VPAID sample tags](https://developers.google.com/interactive-media-ads/docs/sdks/html5/client-side/tags#single-vpaid-2.0-linear). The code being displayed on github should give context for the sample tags, but is not necessary for a publisher's IMA implementation that requests VPAID ads.
