### ISSUE TITLE
Ad replacing <video> src on iOS 12

### ISSUE THREAD

**Issue by mur1s** [googleads/googleads-ima-html5#40]
Hello,

I have a strange issue with the IMA3 SDK on iOS 12. The video ad replaces the source from the main video. Here is an example:

http://staging53.wendyshow.com/ios12bug/

Scenario:
- The main video should autoplay.
- The ad should appear below the main video after 5 seconds (setTimeout()).
- After the ad has ended, the main video should continue playing.

It works as expected on any device I was testing with, except on iOS 12.

Thanks,
Muris

**Comment by asotoglez** [comment]
@mur1s Did you found any solution?

**Comment by mur1s** [comment]
https://github.com/googleads/videojs-ima/issues/769#issuecomment-546016660
