### ISSUE TITLE
What does the adsLoader.requestAds(adsRequest) call return

### ISSUE THREAD

**Issue by niranjala** [googleads/googleads-ima-html5#41]
Can I 
1. adsLoader.requestAds(adsRequest);  - What does this call return. I was reviewing documentation here https://developers.google.com/interactive-media-ads/docs/sdks/html5/v3/apis#ima.AdsLoader.requestAds and am not able to find anything

2. Without using the IMA is this call exposed via an api, where we could make an ad request without having to configure a player and ui ??

**Comment by Kiro705** [comment]
Hello @niranjala ,

1. Nothing is returned by the AdsLoader.requestAds() call.
2. The AdsLoader is an IMA class, so this specific method of requesting ads is limited to using the IMA SDK.

Please feel free to reopen this issue if you have farther questions.
