### ISSUE TITLE
Vpaid Error - Ad error: AdError 901: An unexpected error occurred within the VPAID creative. Refer to the inner error for more info.

### ISSUE THREAD

**Issue by thiyagudev01** [googleads/googleads-ima-html5#42]
Dear,
Am using https://dev.rtb.veuhub.redblink.net/vpaid?pid=10432&consent=[CONSENT]&gdpr=300&width=300&height=250&ua=Mozilla/5.0%20(Windows%20NT%2010.0;%20Win64;%20x64)%20AppleWebKit/537.36%20(KHTML,%20like%20Gecko)%20Chrome/42.0.2311.135%20Safari/537.36%20Edge/12.246 above vpaid tag, but this shows 901 error code in Video Suite Inspector(https://developers.google.com/interactive-media-ads/docs/sdks/html5/vastinspector) and its fired only loaded event , after loaded event it couldn't fire other events , Thanks in advnce

**Comment by Kiro705** [comment]
Hello @thiyagudev01 ,

This question is not related to the IMA HTML5 sample apps. I would recommend reaching out via the [IMA technical forum](url) or to your ad provider for help with this specific ad tag.

Please feel free to reopen this issue if you have any follow-up questions.
