### ISSUE TITLE
Error on running simple example

### ISSUE THREAD

**Issue by mnc-roov** [googleads/googleads-ima-html5#49]
hi, i got this error while running simple example. 

Uncaught SyntaxError: Unexpected identifier
'+V(ky(d))+':1 Failed to load resource: the server responded with a status of 404 (Not Found)
'+V(ky(b))+':1 Failed to load resource: the server responded with a status of 404 (Not Found)
'+V(ky(f))+':1 Failed to load resource: the server responded with a status of 404 (Not Found)
bridge3.389.0_en.html:1032 Uncaught ReferenceError: ima is not defined
    at bridge3.389.0_en.html:1032

how to reproduce:
- clone the googleads-ima-html5
- cd to simple folder
- run the local server with : serve .

**Comment by thowfeeq178** [comment]
try including the  protocol while loading imasdk 
e.g:    
-  <script type="text/javascript" src="//imasdk.googleapis.com/js/sdkloader/ima3.js"></script>
+ <script type="text/javascript" src="https://imasdk.googleapis.com/js/sdkloader/ima3.js"></script>
