### ISSUE TITLE
Don't trigger 'paused' event when clicking on the X button when in fullscreen on mobile

### ISSUE THREAD

**Issue by FrancescoMussi** [googleads/googleads-ima-html5#51]
I am displaying preroll ads on mobile in fullscreen mode.
It works fine.
However there is an issue when clicking on the X button (top left) when in fullscreen mode, since it trigger the `paused` event.

![Screenshot 2020-07-29 at 16 26](https://user-images.githubusercontent.com/5312907/88825415-33c25d00-d1d0-11ea-90c4-ddbc2411c13d.jpg)

I am listening to the pause event and resume the play of the preroll video. 

I would expect the `paused` event to be triggered only when clicking on the pause button.

And I would expect the clicking of the X button to behave in the same way as when pinching the video with two fingers, in which case the video exit the fullscreen mode and keep playing.

What do you think?
Would be possible to avoid to trigger the `paused` event when clicking on the X button?

**Comment by Kiro705** [comment]
Hello @FrancescoMussi ,

There is not currently a way to prevent this behavior from the IMA side. In your tests, if IMA is not loaded, does the video still pause? If this is the case, then IMA is unlikely to be able to change this behavior.
