### ISSUE TITLE
is SDK skipping mid-rolls when user clicks in time line further on in video

### ISSUE THREAD

**Issue by spormeon** [googleads/googleads-ima-html5#55]
if you have pre, mid and post rolls and forward skip to the end of the video by click the time line near end, is it supposed to “skip” the mid-rolls ( as it does), in eg videojs it stops and plays the mid rolls, then comes back to the video at the point you choose in the timeline

This is an issue posted as been asked to by the guys over on AMP-video, issue there , here:
https://github.com/ampproject/amphtml/issues/31263

**Comment by Kiro705** [comment]
Hello @spormeon ,

I tested this behavior using this [ad tag with pre-, mid-, and post-rolls](https://pubads.g.doubleclick.net/gampad/ads?sz=640x480&iu=/124319096/external/ad_rule_samples&ciu_szs=300x250&ad_rule=1&impl=s&gdfp_req=1&env=vp&output=vmap&unviewed_position_start=1&cust_params=deployment%3Ddevsite%26sample_ar%3Dpremidpost&cmsid=496&vid=short_onecue&correlator=) in the [Video Suite Inspector](https://googleads.github.io/googleads-ima-html5/vsi/), and when seeking forward saw that it did snap back and play the mid-roll ad.

If this behavior is still reproducible on your side, please reopen this issue with steps to reproduce.
