### ISSUE TITLE
VMAP Overlay

### ISSUE THREAD

**Issue by aydinkn** [googleads/googleads-ima-html5#6]
Hello,

Nonlinear ads in VMAP not working. When Html5 IMA SDK support it?

**Comment by shawnbuso** [comment]
We don't currently have a timeline for support for nonlinear ads in VMAP. For future questions please refer to our [forum](https://groups.google.com/forum/?hl=en_US&fromgroups#!forum/ima-sdk) where you should expect a faster turnaround time on answers :)
