### ISSUE TITLE
Error running advanced sample v3.431.1-0

### ISSUE THREAD

**Issue by RaiPubblicitaTech** [googleads/googleads-ima-html5#68]
Javascript error running the advanced sample v3.431.1-0

`Uncaught TypeError: Cannot read property 'initialUserAction' of undefined
    at Application.onClick_ (application.js:102)
    at HTMLButtonElement.<anonymous> (application.js:84)`

How to reproduce:
- clone the googleads-ima-html5
- cd to 'advanced' folder
- run the local server
- use any VAST tag (or the built-in sample)

**Comment by Kiro705** [comment]
Hello @RaiPubblicitaTech ,

I was able to follow your steps, but was able to successfully play ads on version [3.470.1-0](https://github.com/googleads/googleads-ima-html5/releases/tag/3.470.1-0). Can you confirm if this is still happening on the latest version?
