### ISSUE TITLE
Icons on mobile do not generates

### ISSUE THREAD

**Issue by SchmidtDawid** [googleads/googleads-ima-html5#69]
i have vast looks like this one (fake links):

> 
>
><VAST version="2.0">
	<Ad id="undefined">
		<InLine>
			<Impression id="">
				<![CDATA[https://fake/event/nc=0/code=29zjtms_JJBoJL6JxcqQlHtqHtn]]>
			</Impression>
			<Impression id="">
				<![CDATA[]]>
			</Impression>
			<Impression id="">
				<![CDATA[]]>
			</Impression>
			<Creatives>
				<Creative id="i4443.mp4">
					<Linear>
						<Duration>00:00:30</Duration>
						<TrackingEvents>
							<Tracking event="start">
								<![CDATA[https://fake/redot.gif?id=p8aVh.d15UqvH_gAAAAA/]]>
							</Tracking>
						</TrackingEvents>
						<MediaFiles>
							<MediaFile type="video/mp4" width="720" delivery="progressive" height="404">
								<![CDATA[ https://fake/http/o2/TVN-Adserver/y2016/v/4e62e752ae53fb6a6eebd0www.mp4 ]]>
							</MediaFile>
						</MediaFiles>
						<Icons>
							<Icon height="404" width="720" xPosition="0" yPosition="0" offset="00:00:00.000" duration="00:00:30.000">
								<StaticResource creativeType="image/jpeg">
									<![CDATA[ https://fake/file/o2/TVN-Adserver/redot.gif ]]>
								</StaticResource>
								<IconClicks>
									<IconClickThrough>
										<![CDATA[ https://fake/hitredir/id=p8aVh.d15UqvHu3nouNqQZYlTIcorvita ]]>
									</IconClickThrough>
								</IconClicks>
							</Icon>
						</Icons>
					</Linear>
				</Creative>
				<Creative />
			</Creatives>
			<AdSystem>TVN</AdSystem>
			<AdTitle>TVN Video Ad</AdTitle>
		</InLine>
	</Ad>
</VAST>

And icon is generated only on desktop mode, but not in mobile. What do i need to do to generate icon on mobile?

**Comment by Kiro705** [comment]
Hello @SchmidtDawid ,

Is this issue specific to the IMA HTML5 sample apps? If it is not, I would recommend reaching out on the [IMA technical forum](https://groups.google.com/g/ima-sdk/). Currently, I don't not believe we have a sample app that parses XML into an ad request.

Please feel free to reopen this issue if you have any follow-up questions.
