### ISSUE TITLE
Could you provide IMA HTML5 SDK sample for game

### ISSUE THREAD

**Issue by cbcye** [googleads/googleads-ima-html5#7]
It is confused when i use IMA HTML5 SDK for game, it is difficult to find any useful information let me use  IMA HTML SDK in my games. there only samples about video. Could you provide official sample about IMA HTML5 SDK for game ?

**Comment by shawnbuso** [comment]
Hi there,

We've got a [support forum](https://groups.google.com/forum/#!forum/ima-sdk) that's better for answering questions like this - we use the GitHub issue tracker for specific issues with the examples hosted here. Would you mind posting your question to that forum so we can follow up with you?

Thanks,
Shawn
