### ISSUE TITLE
Simple integration Question ...

### ISSUE THREAD

**Issue by sktechnology** [googleads/googleads-ima-html5#70]
After analyzing your code I wonder if I need to indicate my adsense account number somewhere or if all this is done automatically with the domain name registered in my account.

I can't find a section that talks about integrating video advertising in my adsense account, I opened a google ad manager account but I'm unable to add adsense as an advertiser, there's probably something I don't don't understand can you help me thanks.

**Comment by Kiro705** [comment]
Hello @sktechnology ,

This is outside of the scope of this IMA sample repo's issue queue. I would recommend asking these types of questions via the [IMA SDK technical forum](https://groups.google.com/g/ima-sdk).

That said, you can reference this [Ad Manager article](https://support.google.com/admanager/answer/1670087) for information on setting up Ad Sense.

Thank you,
Jackson
IMA SDK team
