### ISSUE TITLE
No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://imasdk.googleapis.com' is therefore not allowed access

### ISSUE THREAD

**Issue by rj686** [googleads/googleads-ima-html5#73]
Built an app using www.appyet.com by adding blogger blog rss feed to 'module' option there

Used source files from here (section -simple https://github.com/googleads/googleads-ima-html5/tree/main/simple )

Uploaded ad.js & style.css to server

Changed the ad tag in js file to this ( https://pubads.g.doubleclick.net/gampad/ads?iu=/21775744923/external/single_ad_samples&sz=640x480&cust_params=sample_ct%3Dlinear&ciu_szs=300x250%2C728x90&gdfp_req=1&output=vast&unviewed_position_start=1&env=vp&impl=s&correlator= )

Made necessary changes to html file(ie, linked style.css&ads.js from server), created a new post on blogger, pasted the html code in html section, posted it

App displayed the post, opened the post, clicked play video. Video played without ads. Tried multiple times, no ads

Opened the blog post in google chrome (PC), played the video and ad displayed

Opened the blog post in google chrome (android) played the video and ad displayed

And here's the error code of app's webview in chrome console

////

Failed to load https://pubads.g.doubleclick.net/gampad/ads?iu=%2F21775744923%2Fexternal%2Fsingle_ad_samples&sz=640x480&cust_params=sample_ct%3Dlinear&ciu_szs=300x250%2C728x90&gdfp_req=1&output=xml_vast4&unviewed_position_start=1&env=vp&correlator=718554065969674&sdkv=h.3.521.0&osd=2&frm=0&vis=1&sdr=1&hl=en&afvsz=450x50%2C468x60%2C480x70&is_amp=0&u_so=l&ctv=0&sdki=44d&ptt=20&adk=2341378911&sdk_apis=2%2C7%2C8&omid_p=Google1%2Fh.3.521.0&media_url=https%3A%2F%2Fstorage.googleapis.com%2Fgvabox%2Fmedia%2Fsamples%2Fstock.mp4&sid=67FAAA81-DFB6-4A44-A712-01C43935AECC&nel=0&eid=44725355%2C44752996%2C44754420%2C44760950%2C44761692%2C44762904&url=null&dt=1657973234241&cookie_enabled=1&scor=3777162739521759&ged=ve4_td7_er159.15.318.15_vi0.0.615.360_vp0_eb16488: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://imasdk.googleapis.com' is therefore not allowed access.

////

**Comment by Kiro705** [comment]
Hello @rj686 ,

Based on your debugging, this issue seems to be related to environment of the 'appyet' app. I am not familiar with that, or if it supports IMA. If possible, I would recommend reaching out to their support if IMA is expected to work in their apps, and how you might configure CORS header settings.

Thank you,
Jackson
IMA SDK team
