### ISSUE TITLE
Uncaught error type

### ISSUE THREAD

**Issue by NDULZ** [googleads/googleads-ima-html5#76]
Hi

I receive this error when I place the player on my WiFi's guest portal.

Any help would be most appreciated.

Uncaught TypeError: playButton is null
    init https://portal.example.com:8843/guest/s/default/js/ads.js:19
    <anonymous> https://portal.example.com:8843/guest/s/default/js/ads.js:196

**Comment by Kiro705** [comment]
Hello @NDULZ ,

Is there any code samples you could share, or changes to the sample apps that can help reproduce the issue on my end.

My recommendation would be to make sure the '<button id="playButton">Play</button>' element is properly rendered on the page before making a call to get it by its ID.

Thank you,
Jackson
IMA SDK team

**Comment by NDULZ** [comment]
Hello @Kiro705 

That's what I did, added, window.onload=function init()
Works perfectly now,

Thank you,
Davies
Founder and CEO
Shaeteq
