### ISSUE TITLE
Problem with IMA SDK and ad floor prices 

### ISSUE THREAD

**Issue by FilipLusnia** [googleads/googleads-ima-html5#78]
I have a weird issue - at company, we have a successfully implemented IMA SDK video player, which plays preroll VASTs. There is an issue with ad floor prices though. Whenever I set a floor price for an ad in ADM, the IMA SDK returns 1009 error with empty VAST. It doesn't matter what amount is set - it can even be a fraction, like 0.01 PLN - anything above 0 PLN causes display of empty VASTs. Turning floor price down to 0 PLN or entierly removing the pricing rule from ADM fixes the problem. 

Any help?

**Comment by Kiro705** [comment]
Hello @FilipLusnia ,

Initially, this does not seem like an issue with the IMA SDK but your ad's configuration. There is not any IMA changes that will allow IMA to play ads if it receives an empty VAST.

I may recommend searching on the Ad Manager help center for additional information. I see this article on [Unified pricing rules](https://support.google.com/admanager/answer/9298008) which may be helpful. If you are still having issues, I would recommend reaching out through the Ad Manager help center for additional assistance.

Thank you,
Jackson
IMA SDK team
