### ISSUE TITLE
Is it possible to integrate the IMA SDK to HTML based smart tv platforms?

### ISSUE THREAD

**Issue by Shaharbad** [googleads/googleads-ima-html5#79]
Hey everybody,

I was wondering if theres a method to integrate the IMA SDK to HTML based applications (LG Webos, Samsung TizenTV).

I did tried it on both platforms and got my applications rejected because of a blank screen (even though that on the simulator it was working fine).

When I did some research today I came accros this:
https://groups.google.com/g/ima-sdk/c/ekChugmqT3E
Seems like its being said that it's not supported.

But that comment is from 2019, I wonder if there is a method to make it work.

Thank you.

**Comment by Kiro705** [comment]
Hello @Shaharbad ,

Connected TV platforms are considered as "[additional platforms](https://developers.google.com/interactive-media-ads/docs/sdks/other)" for the IMA SDK.  These platforms support environments where IMA has a feasible SDK, however IMA does not actively test on these platforms, and certain features may not be supported.

I don't have any specific work-around for the blank screen issue you are talking about.

There are future plans to provide IMA support for these platforms, but I don't have any more information at this time.

You may want to reach out on the [IMA technical forum](https://groups.google.com/g/ima-sdk) for more information.

Thank you,
Jackson
IMA SDK team

**Comment by Shaharbad** [comment]
> Hello @Shaharbad ,
> 
> Connected TV platforms are considered as "[additional platforms](https://developers.google.com/interactive-media-ads/docs/sdks/other)" for the IMA SDK. These platforms support environments where IMA has a feasible SDK, however IMA does not actively test on these platforms, and certain features may not be supported.
> 
> I don't have any specific work-around for the blank screen issue you are talking about.
> 
> There are future plans to provide IMA support for these platforms, but I don't have any more information at this time.
> 
> You may want to reach out on the [IMA technical forum](https://groups.google.com/g/ima-sdk) for more information.
> 
> Thank you, Jackson IMA SDK team

Thanks for the response, can you also look into the tvOS IMA SDK sample? It's not working properly

**Comment by Kiro705** [comment]
I would recommend reaching out on the specific GitHub repository you are having issues with, and also identifying the sample/samples that you are having an issue with, and if there are any steps needed to reproduce the issue.

**Comment by Shaharbad** [comment]
> I would recommend reaching out on the specific GitHub repository you are having issues with, and also identifying the sample/samples that you are having an issue with, and if there are any steps needed to reproduce the issue.

I would appreciate  it if you could check it out:
https://github.com/googleads/googleads-ima-tvos-client-side/issues/21
