### ISSUE TITLE
[Skippable Ads] Uncaught (in promise) 

### ISSUE THREAD

**Issue by waiwahGithub** [googleads/googleads-ima-html5#83]
Hello, 
It seems that the IMA SDK did not handle the promise on skippable ads.

The following error thrown non stop until the browser is out of memory.

```
Uncaught (in promise) 
tN {
message: '', 
stack: 'Error\n at new tN (http://imasdk.googleapis.com/…leapis.com/js/core/bridge3.642.0_en.html:295:430)', 
type: 'adPlayError', 
errorMessage: 'The provided ad type: skippablevideo is not supported.', 
errorCode: 200, 
…
}
```

![Screenshot 2024-05-29 at 4 12 17 PM](https://github.com/googleads/googleads-ima-html5/assets/129707059/17792d41-8273-44fa-b3cd-ad4fcdbd0e59)

**Comment by Kiro705** [comment]
Hello @waiwahGithub,

What is the best way to reproduce this issue?

Thank you,
Jackson
IMA SDK team

**Comment by waiwahGithub** [comment]
Hi @Kiro705 ,

Please check out the link for the demo video 
https://drive.google.com/file/d/1cT2JWv_ApRoW5YzcCfhEtaww4nz4fc0M/view?usp=sharing

We have modified the simple zip and change only the `adTagUrl` to 

```
https://pubads.g.doubleclick.net/gampad/ads?sz=1920x1080|1024x768&iu=4654/mewatch_ctv_webos_staging/episode/340/5/Medium&vid=316557&cmsid=2666983&correlator=1717057683&description_url=https%3A%2F%2Fstag9.mewatch.sg%2Fwatch%2FRideEatFind-E2-Tanjong-Pagar-36238&url=https%3A%2F%2Fstag9.mewatch.sg%2Fwatch%2FRideEatFind-E2-Tanjong-Pagar-36238&env=vp&gdfp_req=1&output=xml_vast4&cust_params=product%3DNA%26medialanguage%3DEN%26mediarights%3DLM%26genre1%3DIND%26genre2%3Dnoad_tif%26genre3%3DNA%26mediaid%3D316557%26seriestitle%3DRide.Eat.Find%26seriesid%3D323274%26UID%3DNA%26meid%3Df09e2398-b2f9-4033-a085-4f619377406e%26meid_seg%3Ds283%2Cs284%2Cs368%2Cs424%2Cs467%2Cs474%2Cs480%2Cs492%2Cs510%2Cs518%2Cs577%2Cs589%2Cs591%2Cs592%2Cs593%2Cs594%2Cs595%2Cs596%2Cs597%2Cs598%2Cs600%2Cs609%2Cs611%2Cs630%2Cs632%2Cs662%2Cs721%2Cs722%2Cs723%2Cs726%2Cs755%2Cs758%2Cs759%2Cs760%2Cs761%2Cs762%2Cs764%2Cs765%2Cs766%2Cs767%2Cs768%2Cs769%2Cs771%2Cs772%2Cs773%2Cs774%2Cs776%2Cs777%2Cs778%2Cs779%2Cs780%2Cs782%2Cs784%2Cs785%2Cs826%2Cs919%2Cs926%2Cs929%2Cs930%2Cs931%2Cs932%2Cs944%2Cs945%2Cs946%2Cs992%2Cs1019%2Cs1020%2Cs1021%2Cs1022%2Cs1023%2Cs1025%2Cs1041%2Cs1288%2Cs1289%2Cs1290%2Cs1295%2Cs1296%2Cs1297%2Cs1299%2Cs1378%2Cs1385%2Cs1392%2Cs1394%2Cs1396%2Cs1398%2Cs1400%2Cs1401%2Cs1412%2Cs1414%2Cs1416%2Cs1418%2Cs1425%2Cs1436%2Cs1440%2Cs1445%2Cs1446%2Cs1447%2Cs1448%2Cs1537%2Cs1539%2Cs1672%2Cs1687%2Cs1699%2Cs1704%2Cs1707%2Cs1708%2Cs1799%2Cs1805%2Cs1824%2Cs1826%2Cs1863%2Cs1969%2Cs1991%2Cs1992%2Cs2009%2Cs2029%2Cs2030%2Cs2031%2Cs2032%2Cs2033%2Cs2034%2Cs2069%2Cs2084%2Cs2086%2Cs2100%2Cs2114%2Cs2120%2Cs2122%2Cs2125%2Cs2130%2Cs2132%2Cs2133%2Cs2134%2Cs2136%2Cs2137%2Cs2138%2Cs2139%2Cs2140%2Cs2141%2Cs2143%2Cs2145%2Cs2146%2Cs2147%2Cs2148%2Cs2149%2Cs2150%2Cs2152%26profiletype%3DNA%26kidscontent%3DNA%26mediatitle%3DRide.Eat.Find%20-%20S1E2%26noadflag%3DFree%26lotameId%3DNA%26classification%3DIMDA-G%26os%3Dwebos%26ver%3Ddev&plcmt=1
```
[simple.zip](https://github.com/googleads/googleads-ima-html5/files/15495997/simple.zip)

Expectation: After preroll it going to throw the error, please refer to the demo video.


**Tested On:**
**Operating system**: MacOS Sonama 14.5
**Chrome**: Version 125.0.6422.112 (Official Build) (arm64)

**Comment by Kiro705** [comment]
Hello @waiwahGithub ,

I downloaded the sample.zip you shared, and was able to run the sample app without encountering the error. Are there any additional steps needed to reproduce the issue? I am also testing on MacOS and with Chrome.

Thank you,
Jackson
IMA SDK team

**Comment by waiwahGithub** [comment]
Hi @Kiro705 ,

sorry for missing out the critical extension.
![Screenshot 2024-05-31 at 10 06 32 AM](https://github.com/googleads/googleads-ima-html5/assets/129707059/f17a062b-677e-4bfd-93e6-0fd222c0593e)
You need this to emulate the environment where skippable ads is not supported (chrome extension)

Thank you.

**Comment by Kiro705** [comment]
Hello @waiwahGithub ,

Thank you for adding those details. I was able to see the the issue with the repeating error when using the ad tag with the extension. I also tested the same ad tag + extension with the [IMA VSI player](https://googleads.github.io/googleads-ima-html5/vsi/) and saw the issue there. I think this may be an issue with the IMA SDK and not specific to the sample apps. If there is a fix we can make in the sample apps, please follow up in this thread, and I can look into implementing those changes.

If it is an issue with the IMA SDK itself, I recommend raising the issue on the [IMA SDK technical forum](https://groups.google.com/g/ima-sdk). That is the best place to raise issue with the IMA SDK.

**Comment by waiwahGithub** [comment]
Hi @Kiro705 ,

Thanks for your help in identifying the issue with the ad tag and extension. 
Since it is related to the IMA SDK itself, I will raise the issue to [IMA SDK technical forum](https://groups.google.com/g/ima-sdk).

Thank you so much.
